# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama 3 8B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"
enable_ibm_wandb = false
wandb_dir = "./wandb"
wandb_project_name = "8b-test"  # to be switched to prod name once tested
wandb_run_id = "8-test-1"  # to be switched to prod name once tested

[model]
name = "llama3"
flavor = "8B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "meta-llama/Llama-3.1-8B"

[optimizer]
name = "AdamW"
lr = 3e-4

[training]
seed = 2024
batch_size = 1
seq_len = 8192
warmup_steps = 200  # lr scheduler warm up
max_norm = 1.0  # grad norm clipping
epochs=1.0
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "c4_test"
sum_loss = true

[dataset]
datasets = "/gpfs/goon/data/open_instruct/llama_3p1_8b_tulu/90f324b6ba"
dataset_weights = 1.0

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'

[float8]
enable_float8_linear = false
