# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "/gpfs/lchu/titan"
description = "Llama 3 70B training"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = false
save_tb_folder = "tb"
enable_ibm_wandb = false
wandb_dir = "/gpfs/lchu"
wandb_project_name = "70b-test"  # to be switched to prod name once tested
wandb_run_id = "70b-test-1"  # to be switched to prod name once tested

[model]
name = "llama3"
flavor = "70B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "/datasets/tokenizers/llama3"

[optimizer]
name = "AdamW"
lr = 1.5e-4

[training]
seed = 2024
batch_size = 1
seq_len = 8192
warmup_steps = 200
max_norm = 1.0  # grad norm clipping
epochs=1.0
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 2  # 8-way TP
compile = true
dataset = "c4"

[dataset]
datasets = "/gpfs/goon/data/open_instruct/llama_3p1_8b_tulu/4ba4a38f44_filtered"
dataset_weights = 1.0

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 1000
model_weights_only = false
export_dtype = "float32"
async_mode = "async" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'

[float8]
enable_float8_linear = true
enable_fsdp_float8_all_gather = true
precompute_float8_dynamic_scale_for_fsdp = true
